title: "John Doe"
description: "Personal web site and profile page of John Doe, a researcher and artist."
keywords: ["John Doe", "jdoe", "homepage", "personal", "resume", "CV"]

author:
  name: "John Doe"
  position: "Researcher"
  affiliation: "Organization"
  email: "john (dot) doe (at) mail (dot) com"
  image:
    path: "/assets/img/qr.png"
    alt: "QR Code"

footer:
  show-theme-source: true

# Where to pull assets from
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - assets

# Collections
collections:
  publications:
    output: true
    permalink: /publications/:year/:title/
  projects:
    output: true
    permalink: /project/:name/
  portfolio:
    output: true
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: publication
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: portfolio
    values:
      layout: portfolio-item
# Plugins
plugins:
  - jekyll-sitemap
